### PR TITLE
group jobs in Spark UI by dataset and action type (#1184)

### LINKED ISSUE #1184: Use SparkContext.setJobGroup to categorize jobs created by SMV
When I say jobs, I mean it in the sense that Spark uses it, which can be roughly equated with an action on `DataFrame`. When you look in the Spark web UI for an application, not a lot of information is given about the job that's triggering an action. Sometimes you get 
```
saveAsTextFile at SmvMetaData.scala:141 
```
and sometimes you just get
```
run at ThreadPoolExecutor.java:1149
```

SMV should "group" the jobs to provide more context.

https://stackoverflow.com/questions/39123314/how-to-add-custom-description-to-spark-job-for-displaying-in-spark-web-ui

### PR DESCRIPTION
**Pull request by laneb**
Resolves #1184.
screen shot 2018-04-11 at 11 37 55 pm

### CODE REVIEW

**Comment by jacobdr** [comment]
Wow. Game changer.

**Comment by laneb** [comment]
😁

**Comment by ninjapapa** [comment]
It is so cool!

**Comment by AliTajeldin** [comment]
This is soooooo cooooooool.

**Pull request merged**
