### PR TITLE
I657 gendoc in release

### PR DESCRIPTION
**Pull request by AliTajeldin**
#657 update `smv-install` to integrate generation and publishing of docs into release script.

PS: will need to delete the two old scripts once script has been tested on a real release.

### CODE REVIEW

**Comment by laneb** [comment]
Looks good.

**Comment by Khorkhe** [comment]
In order to release v1.6.2, I had to add py4j (pip install py4j) in the virtual environment. You may want to add that to the list of requirements. v1.5.2 does not require it though.

**Comment by AliTajeldin** [comment]
@Khorkhe We should be using the py4j from the spark version (we add the following to python path in the release script `${spark_py_dir}/lib/py4j-0.8.2.1-src.zip`).  My guess is that the 1.6 version used a different py4j version which means we were not picking it up from spark lib dir.
I'll modify the code to use a glob pattern instead.

**Comment by Khorkhe** [comment]
sounds good!

**Comment by AliTajeldin** [comment]
Added glob pattern matching for py4j lib.

**Pull request merged**
