### PR TITLE
I1293 fix version number matching

### LINKED ISSUE #1293: Fix bad search and replace in `smv-release`
When updating the SMV version, `smv-release` does
```
  # update version in user docs.
  find docs/user -name '*.md' \
    -exec perl -pi -e "s/${PREV_SMV_VERSION}/${SMV_VERSION}/g" \{\} +
```
neglecting the fact that `.` is a wildcard. The result is a lot of bad replacements, like
```
-    "java.lang.NumberFormatException: For input string: \"001x\" @RECORD: 123,001x  ,20130109130619,12102012"
+    "java.lang.NumberFormatException: For input string: \"001x\" @RECORD: 123,001x  ,2.2.0.09130619,12102012"
```
Need to fix all of the bad replacements (see #1272 for some examples) and as well as fix the bug.

### PR DESCRIPTION
**Pull request by tianruiwang**
Fixes #1293 
When updating smv version number in the docs, each dot `.` in `SMV_VERSION` will be parsed to `\.` to match the actual dot instead of an regex wildcard. e.g. `/2.3.0.0/g` -> `/2\.3\.0\.0/g`.

I have tested these changes manually by entering the `perl -pi -e` commands, but a full test would require making a new release. Shall we make a release to test this?

### CODE REVIEW

**Comment by tianruiwang** [comment]
Changes done, I searched through the whole SMV with pattern `[0-9]\.[0-9]\.[0-9]\.[0-9]` and filtered these suspicious ones out, which are also exactly the same replacements being mistakenly made in #1293.

**Comment by laneb** [comment]
Cool, lgtm.

**Comment by tianruiwang** [comment]
Btw these are the remaining matchings, please take a peek to make sure there isn't anything left
smv_1

**Comment by laneb** [comment]
Looks like the docs have some references to v1.5.2.8. That's incorrect but unrelated.

**Comment by AliTajeldin** [comment]
the tests are failing but it is due to new config param and not this PR.  Merging.

**Pull request merged**
