### PR TITLE
I1390 rm data set mgr

### LINKED ISSUE #1390: Move DataSetMgr to Python
Child of #1338 

Currently python side already created a `DataSetMgr` interface, although it simply call Scala side `DataSetMgr`. This issue is to remove scale side `DataSetMgr` totally.

### PR DESCRIPTION
**Pull request by ninjapapa**
Fixed #1390 

Moved `DataSetMgr` and `TX` to Python. `DataSetResolver`, and `DataSetRepo` framework are still in Scala. They will be moved when we are ready to move the `SmvDataSet` class fully.

### CODE REVIEW

**Comment by ninjapapa** [comment]
Found a bug. Close to fix.

**Comment by ninjapapa** [comment]
Close to add back appDir to Scala side temporarily.

**Comment by AliTajeldin** [comment]
Hmm, CI failed because it couldn't find sbt.

**Comment by ninjapapa** [comment]
I think the CI server is down or almost down.

**Comment by AliTajeldin** [comment]
ok, will test both PRs on my machine and will merge if it works.  I shall be "Travis" for the day.

**Pull request closed without merging**
