### PR TITLE
I1074 Persist DQMState inside DqmValidationResult

### LINKED ISSUE #1074: Persist DQMState in DqmValidationResult
See #1062

### PR DESCRIPTION
**Pull request by Kai-Chen**
Closes #1074 

#### Summary
- Created a value object class `DqmStateSnapshot` to simplify json {de}serialization.

### CODE REVIEW

**Comment by AliTajeldin** [comment]
@Kai-Chen looks like CI is failing for non-resource related issue.

**Comment by Kai-Chen** [comment]
Yep, I'm on it.

**Comment by Kai-Chen** [comment]
Odd ... passes on my dev box.
Digging deeper into it.

**Comment by Kai-Chen** [comment]
Ack, didn't run `sbt assembly` before smv-pytest, so I was testing against the old fat jar -- that's my curse word of the day :)
Should work now.

**Pull request merged**
