### PR TITLE
Issue/645

### PR DESCRIPTION
**Pull request by hubertp-lshift**
Issue #645

### CODE REVIEW

**Comment by hubertp-lshift** [comment]
Looks like a spurious error on one of the executors.

**Comment by AliTajeldin** [comment]
@hubertp-lshift Please add some documentation to the scalaFmtOnCompile plugin so it can be maintained.  Also, would using this plugin require network connectivity when compiling?  Is it sufficient to just be connected once for the first compile or would it try to check the version on every compile?

**Comment by hubertp-lshift** [comment]
@AliTajeldin Done. It fetches and caches the downloaded artifact AFAIK.

**Comment by AliTajeldin** [comment]
@hubertp-lshift Any idea why Travis build is failing on this branch?  The error seems cryptic.

**Comment by hubertp** [comment]
I fixed source conflicts (latest master) but the error seems to be related to JDK incompatibility. You are using 1.7 in travis, but scala.meta (dependency of scalafmt) seems to rely on some 1.8 API. Any chance you could upgrade?

**Comment by AliTajeldin** [comment]
We are stuck with Java 7 for the 1.5 branch (current master) due to client requirements.  However, we are switching to JDK 8 for the 2.1 branch.  I'll hold off on merging this into master once 2.1 is merged into master any day now, no really :-)  I know, we have been saying that for the last two weeks :-)

**Comment by AliTajeldin** [comment]
Closing as we don't have the expertise in-house to maintain.

**Pull request closed without merging**
